version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /home/jamilson.pereira@VALEMOBI.CORP/Documentos/DesenvolvimentoClass/Docker-Compose